### PR TITLE
Updated gitignore, more work on translations

### PR DESCRIPTION
**Pull request by NastyGamer**
Just a small pull request to make sure the way I do this is correct.
Firstly, I updated to gitignore file to include rules for macOS, Windows and Linux.
Secondly I tried translating the File menu in English and German.
Please give me feedback whether the way I'm currently doing these translations is correct.

### CODE REVIEW

**Comment by lbalazscs** [comment]
Yes, this is basically what I had in mind! Keep up the good work!

Some comments:
- it is not necessary to indent the entries of the submenus (as you did in the English version of the Automate submenu), but it is also not a problem
- it would be helpful if you added the comments (such as "#Edit menu") in the translated files (of course the comments don't have to be translated, they will not be visible by users) so that things are easier to find
- English language GUIs use "title case", so for example if it was "Batch Resize", don't replace it with "Batch resize" (lower case R) in the English file. I don't know what's the convention for German-language GUIs
- I know some German, and I think "vergrößern" means to make it bigger, but typically "Batch Resize" will be used to make the images smaller

I am also starting to rewrite Pixelitor to take these strings from the files instead of hardcoding them.
If you have any questions, feel free to comment on https://github.com/lbalazscs/Pixelitor/issues/97 or to open new issues.

**Comment by NastyGamer** [comment]
Thank you for your feedback! I will definitely continue to improve these translations!

**Comment by lbalazscs** [comment]
The file lookup keys are working now in the latest GitHub version. In the meantime I found two other small issues:

- "Open" and "Clear Recent Files" are still missing from the translations ("Clear Recent Files" is the last entry in the "Recent Files" submenu, and clears the recent files, without deleting them from the disk). 
- in the English the "Exit" menu has two names: it is called "Quit" on Macs (a Mac convention) and "Exit" on other operating systems, so there should be also an exit_mac key (you can set it to the same Verlassen if you can't check on a German Mac, it's not a big deal) 

file_german

**Comment by NastyGamer** [comment]
Thanks for the heads up! I'll fix it as soon as possible. (Looks awesome BTW)

**Pull request merged**
