### PR TITLE
Can we please have some basic Project Integration support?

### PR DESCRIPTION
**Pull request by Minecraftian14**
Hello there, I am new to Java programming and I like creating small projects as fun 😃.

Please excuse me if I used the wrong term, "Project Integration". What I really meant was some sort of support to get an application to start Pixelitor with some arguments to use it as an external editor for certain images.

I tried playing around with the code of Pixelitor and came up with this solution:
When parsing the command-line args, check for a specific argument value -PI. All the file paths after that are not to be opened right away, but instead have a separate MenuItem for them.

I know, my code must be very inefficient and useless, so feel free to dispose of this issue. But I request you to add in this feature 😅

### CODE REVIEW

**Comment by lbalazscs** [comment]
Hi! Just as I had time to look at this, you already closed the pull request... I assume this means that you are no longer interested. If you still are, then please open an issue or start a discussion. 

BTW, if you just want to have menu items for specific files, then a hack would be to write your files using the Preferences API as "recent files" (just like Pixelitor does), then start Pixelitor, and your files should be in the recent files menu, ready to be opened with a click. And of course if you start Pixelitor by listing the files on the command line, Pixelitor will open all of them when starting.

**Comment by Minecraftian14** [comment]
Yeah, I had it all working perfectly 😍
It's just when you do anything related LibGDx, no Swing app will work out of the box 😭

Otherwise, I would have loved to contribute and learn new things in java!
I already found so many interesting things in this project like Optional, CompletableFuture, Asynchronous execution... 😅

Anyway, thanks a lot for your welcoming reply! Let me just state the idea behind this request and the issue, you may ignore it...

There is an application called Hyperlap2D which is used to design 2D maps (in scene2D) for LibGDx games.
I thought who wouldn't want an in-app plugin to easily edit all the images in their project. 
So I tried making a plugin which will simply run Pixelitor with the press of a button in Hyperlap!

While at that, I also wanted to add in "very simple" project integration stuff. And I was somewhat successful too!

In an ordinary java application (like just plain java, no external stuff) I can just use the following codeline to start Pixelitor as desired:
Runtime.getRuntime().exec("java -jar path/to/jar/Pixelitor.jar");

But due to "reasons", in the gdx application, Pixelitor either doesnt start at all, or when it starts this happens:
1. The Tips popup welcomes us.
2. I press "close" button.
3. Pixelitor freezes, nothing is responsive at all.

**Comment by Minecraftian14** [comment]
So.... to conclude, I can open the issue again if you think "nevertheless, the feature is good to have!" 😁

Once again, thanks a lot 👍

**Comment by lbalazscs** [comment]
I think that simply adding a "Project" menu item to Pixelitor would be confusing for the users who just want to use it as an image editor, and have their own ideas about what a project is. Some sort of plugin architecture would be needed (so that this menu only appears when the "project integration" plugin is loaded), but Pixelitor currently doesn't have that. 

I have no idea why Runtime.getRuntime().exec() isn't working in a libgdx app. You could try embedding all of Pixelitor in your Hyperlap2D plugin (as long as it is GPLv3-licensed), and simply call Pixelitor.main as if it was a utility method, with the file paths as the string array argument. This way you could easily add or change anything, but if you change things, it would be more difficult in the future to upgrade to newer versions of Pixelitor.

**Comment by Minecraftian14** [comment]
Oh no!!

Please try out the test file named "" in this pull request!

The project menu item is visible only when project integration is used, ie, the application run with "-PI" argument!

**Comment by Minecraftian14** [comment]
Yeah, I could have tried making the code of Pixelitor, itself a plugin so that I could call it's main method.

But then no one would have ever accepted that as a pull request 😅. Just for info, adding in the dependencies of making s plugin is pretty much heavy.

**Comment by Minecraftian14** [comment]
Ah just to continue:

java -jar Pixelitor.jar a.png b.png
Will open the images in editor.
There will be no Project menu item!

java -jar Pixelitor.jar -PI a.png b.png
This will not open the images, but just add their names in a menu aside file menu, which will let access to project images.
And now, the project menu is visible.

java -jar Pixelitor.jar a.png -PI b.png
This will open a.png and add b.png to Project menu.

**Comment by lbalazscs** [comment]
It's hard to believe that the project menu item is currently visible only when the application is run with "-PI" argument, because your changes to MenuBar.java call ```add(createProjectMenu());``` without checking any condition... But I agree that in principle this way the menu item could be added without confusing the normal users. (Although even in this case as a user I would prefer to have the files automatically opened)

But all this doesn't matter if you can't use it anyway. 

In the future it might become possible to send files to be opened to an already running Pixelitor process, see issue #163. Perhaps that would be the best workflow for Hyperlap2D users, because they would have the ability to switch between the two apps without waiting for Pixelitor to start, and without having to decide in advance the files they might want to open.

**Comment by Minecraftian14** [comment]
"it's hard to believe"
Well, I did tested it😆 and it's working 👍

What happens is, the project menu is created and added, but it's not visible because `setVisible(false)`.

If -PI had been used, a file will have to be added to it! And that's when it's set to visible.

**Comment by Minecraftian14** [comment]
"Although even in this case as a user I would prefer to have the files automatically opened"

Absolutely no 😅. No one would want all 100s or even 1000s of images to be listed right away when you open Pixelitor 😆

**Comment by Minecraftian14** [comment]
"In the future it might become possible to send files to be opened to an already running Pixelitor process, see issue #163"

That's great! It should work...

But well, no idea of it will work, when launched with libgdx app 😅

Btw, I am curious how will that happen?

**Comment by lbalazscs** [comment]
> What happens is, the project menu is created and added, but it's not visible because setVisible(false).

Oh, sorry, I didn't notice it. 

> No one would want all 100s or even 1000s of images

For so many images, you would need hierarchical submenus, probably corresponding to the directory structure on disk, and also preview images, and at this point you are just re-implementing the Open dialog. 

If you want the open dialog to start at a specific directory, you can achieve this by writing into the Pixelitor preferences because the last used open directory is saved.

BTW, some generic image browser/viewer would be a welcome addition to Pixelitor if it had more features than the open dialog, but it would be a lot of work.

> Btw, I am curious how will that happen?

I was thinking about sending file names using Unix domain sockets. This way even non-java clients could send file names to be opened to Pixelitor, but only from the local machine. A disadvantage is that on Windows this can work only starting from Windows 10. The rest of Pixelitor works fine on Windows 7 or 8.1

**Comment by Minecraftian14** [comment]
> For so many images, you would need hierarchical submenus, probably corresponding to the directory structure on disk
Yeah, at this point, hyperlap only allows you to have all images in one flat directory.
Hopefully it will change in the future.
Currently the issue is, that the Menu drop is not scrollable, I believe that can be fixed.

**Comment by Minecraftian14** [comment]
> If you want the open dialog to start at a specific directory, you can achieve this by writing into the Pixelitor preferences because the last used open directory is saved.
Yeah, that's a pretty good idea, (But now i am using Novix, sorry 😅)

**Comment by Minecraftian14** [comment]
> BTW, some generic image browser/viewer would be a welcome addition to Pixelitor if it had more features than the open dialog, but it would be a lot of work.
I don't really get what exactly you are saying here, but you know what, I really love Swing 😁
If not in one day, I can create it in 2 weeks at max!
Only problem is, that I have not much experience coding "efficient" things 😗

If you have a flexible time scope, I can try it 😁

**Comment by Minecraftian14** [comment]
"Unix domain sockets" 🤯
Never heard of that scary term...
|| It's okay, no explanations needed, I'll do my own research when I have time😅 ||

**Comment by lbalazscs** [comment]
> Yeah, at this point, hyperlap only allows you to have all images in one flat directory.

Then some sort of search could be useful, like the as-you-type thing I did for searching filters (in Filter/Filter Search). 

> Currently the issue is, that the Menu drop is not scrollable, I believe that can be fixed.

It can, like in https://tips4java.wordpress.com/2009/02/01/menu-scroller/
But for me it would still be a bad user experience if I had to manually scroll through 100-1000 items...

> But now i am using Novix, sorry 

Isn't Novix an Android editor? Anyway, if you found a solution for the original problem that doesn't use Pixelitor, I'm glad...

> I don't really get what exactly you are saying here, but you know what, I really love Swing

I was just trying to say that I prefer generic features, that are useful for all users. A magic -PI flag is useful only for your plugin, but an image browser would be visible (and hopefully useful) for all users, perhaps including your plugin. In this sense I would "welcome" such a pull request with more enthusiasm...

> If not in one day, I can create it in 2 weeks at max!

I guess the required time depends on the number of features it would have (for example Adobe Bridge has a large number of features, that would take years), but I would certainly be glad to accept anything that is better than the open dialog (for example something with a search feature). 

BTW, there are already some open-source Java projects that implement some sort of image browser/viewer, for example this might give some ideas: https://sourceforge.net/p/jiexplorer/code/HEAD/tree/trunk/

> Only problem is, that I have not much experience coding "efficient" things

Don't worry, this is not an exam. If you contribute something useful, then it's great. If I see some opportunity to improve it, then I will, without blaming you. I improve my own code all the time...

> If you have a flexible time scope, I can try it

I have all the time in the world...  I might release a version 4.2.4 sometime in the not-very-far future. But even if this contribution (or any other contribution) misses it, there will be other versions in the future.

**Comment by Minecraftian14** [comment]
"Then some sort of search could be useful, like the as-you-type thing I did for searching filters (in Filter/Filter Search)."

Brilliant😆

"Isn't Novix an Android editor? Anyway, if you found a solution for the original problem that doesn't use Pixelitor, I'm glad..."

Yeah Novix is an Android app .. And a gdx app 😅

But it's source was available on GitHub. Unfortunately there were millions of issues with it like, incompatible gdx, class not found, reflection issues and all. Only after that I came to Pixelitor 😆.
But unfortunately that didn't work either. So I decided, it's best i try debugging Novix, and after a while day of fixing errors it laughed 🎉

I am still open to Pixelitor, because well, it's a damn better editor for images 😆

"I was just trying to say that I prefer generic features, that are useful for all users. A magic -PI flag is useful only for your plugin, but an image browser would be visible (and hopefully useful) for all users, perhaps including your plugin. In this sense I would "welcome" such a pull request with more enthusiasm..."

Ah that! Well having -PI ain't that bad, because (as far as I know) it's not hindering the normal usage! Neither of appears to normal users. And "maybe" one can create more plugins, like for Unity, Idea... using Pixelitor.

A general Image Browser, is it something like:
A JFileChooser like popup, which allows you to quickly browse through images with certain filters for file name, extension, date and all....

"BTW, there are already some open-source Java projects that implement ..."

I assume you want an implementation in your project itself instead of depending on an external library?




Thanks a lot 😊 for this great welcome 😅🙏

**Comment by lbalazscs** [comment]
> A general Image Browser, is it something like:
> A JFileChooser like popup, which allows you to quickly browse through images with certain filters for file name, extension, date and all....

Yes. I mean I wouldn't mind any feature that is present in Adobe Bridge (if you're not familiar with it, you can watch some youtube video about it for ideas). Whatever you think it would be reasonably easy to implement and useful for Pixelitor's users.

Also if you don't have a clear wish other than doing interesting things with Swing, then please note that inside Pixelitor there are a lot of things that could be improved as well. Just one example: the "Enlarge Canvas" dialog is not very intuitive in my opinion, it would be better if the controls were somehow at the north, south, east, west, and there was some preview that illustrated how the canvas size will change. And if you happen to like the Java2D API as well (basically just the Graphics2D class), then there are a lot of interesting filters (for example maze generation) that require only some invested time, and no deep image-processing skills. If you are interested, let me know, I'll help you to get started.

> I assume you want an implementation in your project itself instead of depending on an external library?

An external library is fine for me. There are lots of possibilities: 
 - direct pull request to Pixelitor
 - external library (in Maven Central) that is used by Pixelitor
 - external app that can start Pixelitor and/or send file paths to it

**Comment by Minecraftian14** [comment]
I have not yet seen what "Enlarge Canvas" is in Pixelitor, I'll sure give it a look 👍

Not really a fan of Graphics2D, but yeah I know little bit 😅

**Comment by lbalazscs** [comment]
"Canvas" is basically the image size. When you use the move tool, you can move a part of a layer outside the canvas (hiding it), but the saved image has always the size of the canvas. "Enlarge Canvas" is the opposite of crop: it adds empty space around an image or makes the hidden part of the image visible. Technically this would be changing the EnlargeCanvasPanel class, which is a static inner class inside the EnlargeCanvas class. 

Note that this was just an idea, I asked myself "what would be a relatively easy swing-only improvement for someone, who is not very familiar with the codebase", and this was the first thing I could think of...

**Comment by Minecraftian14** [comment]
I have used Photoshop😅 so it's relatable.

Btw, can we have done other place to discuss? Something like discord...
Because he we take "24" hours just to exchange one message

**Comment by Minecraftian14** [comment]
Haha, I will make sure I'll understand the code base better whole at this

**Comment by lbalazscs** [comment]
I registered on Discord (same username as here) and I sent a friend request

**Comment by Minecraftian14** [comment]
Awesome

**Pull request closed without merging**
