### PR TITLE
Add possibility to draw guidelines in crop rect

### PR DESCRIPTION
**Pull request by LucasTheCure**
Added selector in settings panel with 3 most useful design helper guidelines.

### CODE REVIEW

**Comment by LucasTheCure** [comment]
After upgrading **mockito**, 

I have issue while testing single test file. If I build and test everything pass successfully (strange situation)

Have you any problems with: 
 - import static **org.mockito.ArgumentMatchers.any;**
 - should not it be??: **import static org.mockito.Matchers.any;**

**Comment by lbalazscs** [comment]
I don't think it is Mockito, Matchers is deprecated anyway. I remember vaguely that it happened before that the tests were dependent because of some stuff in shared static fields, and the exact order of execution mattered. Interestingly I also have strange problems in CompositionCreationTest since I pulled your changes, although you didn't change anything related (I did, but it worked before I pulled). Very strange, I am looking into it. I'm pretty sure that the problem is in my code, not in yours. Exactly which test file is failing for you when tested alone?

BTW, the guidelines are a very useful  feature, as always, although maybe the default should be still "None". Or the choice could be a saved used preference.

**Comment by lbalazscs** [comment]
I think I fixed the test situation with my latest commit. I tried to run every file with junit tests individually, I fixed one file, and I set two tests in another one to Ignore, because I have to analyze them further. Please let me know if you still have problems any with the tests.

About Matchers: https://static.javadoc.io/org.mockito/mockito-core/2.2.7/org/mockito/Matchers.html

One more idea about the Crop Tool: I think the mouse cursor should change to move cursor when it is inside the handles area, to remind the user that the area can be dragged around. Just an idea, I would try to do it, but I am trying to avoid that code in order to avoid merge conflicts.

**Comment by LucasTheCure** [comment]
I had problems with InteliJ IDEA, somehow it run single test file with mockito v1, After reconfiguration it works as it should. I have added MR to replace deprecated mockito calls.

**Comment by LucasTheCure** [comment]
As for enhancements:

1. Guidelines defaults as "None". As a photographer I like guidelines and always use them, but maybe that's my preference and not overall needs. "None" probably will be cleaner default setting.

2. Move cursor in crop rectangle?: good idea

**Comment by lbalazscs** [comment]
I also use IntelliJ IDEA. Somewhere there is a setting to always use the Maven configuration file for project settings - I guess this is what you have now. 

If it annoys you that as a user you always have to set the guidelines, feel free to use the AppPreferences to save this setting between sessions (things like the foreground color are already preserved). Also as a developer, if you want some actions to be automatically executed every time you start the program, the afterStartTestActions method in the Pixelitor is a good place for that. Activating the crop tool would be

clickTool(Tools.CROP);

**Pull request merged**
