### PR TITLE
Create it.po

### PR DESCRIPTION
**Pull request by albanobattistella**

### CODE REVIEW

**Comment by lbalazscs** [comment]
Great, merged! Grazie! I will add Italian to the languages in Preferences in a moment, and I also plan a beta release soon, which will include this translation.

**Comment by albanobattistella** [comment]
> Great, merged! Grazie! I will add Italian to the languages in Preferences in a moment, and I also plan a beta release soon, which will include this translation.

thanks to you!
after that, I wont to refine the translation.
Regards,
Albano  :-)

**Comment by lbalazscs** [comment]
The beta release is here: https://github.com/lbalazscs/Pixelitor/releases/tag/v4.2.4-beta1
Note that it's not necessary in my opinion to put the license header in texts_it.properties. It was my fault that it was there in the English and German versions (my IDE put it there when I was not paying attention...), but I removed them now. I didn't remove from the Italian version in order to avoid version conflicts. Anyway, it's not a big deal.
Regards,
Laszlo

**Comment by albanobattistella** [comment]
Hi,

thanks for the news.
I'll test it.

Regards,
Albano
________________________________
Da: László Balázs-Csíki <notifications@github.com>
Inviato: domenica 17 gennaio 2021 00:41
A: lbalazscs/Pixelitor <Pixelitor@noreply.github.com>
Cc: albanobattistella <albano_battistella@hotmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [lbalazscs/Pixelitor] Create it.po (#149)


The beta release is here: https://github.com/lbalazscs/Pixelitor/releases/tag/v4.2.4-beta1
Note that it's not necessary in my opinion to put the license header in texts_it.properties. It was my fault that it was there in the English and German versions (my IDE put it there when I was not paying attention...), but I removed them now. I didn't remove from the Italian version in order to avoid version conflicts. Anyway, it's not a big deal.
Regards,
Laszlo

**Pull request merged**
